### ISSUE TITLE
Keeps Reconnecting 

### ISSUE THREAD

**Issue by trimmytech** [olubunmitosin/laravel_flutter_pusher#13]
Hello , first of all, thank you for this wonderful package.
 
Any time i use the below code , my app connect to the laravel websocket succesfully on android but nothing happens on ios :

var options = PusherOptions(
        host: PusherConfig.host, port: 6001, encrypted: false, cluster: 'eu');

    LaravelFlutterPusher pusher = LaravelFlutterPusher(
        PusherConfig.appKey, options,
        enableLogging: true);
    //
    pusher
        .subscribe('channel')
        .bind('event', (event) => print('event =>' + event.toString()));

so i decide to use it with laravel_echo package , maybe that is the issue but anytime i combine the code with the echo , it doesnt work , it just keep writing connecting....reconnecting..connecting....reconnecting..connecting....reconnecting....

below is the code with echo 

var options = PusherOptions(
        host: PusherConfig.host, port: 6001, encrypted: false, cluster: 'eu');

    LaravelFlutterPusher pusher = LaravelFlutterPusher(
        PusherConfig.appKey, options,
        enableLogging: true);

Echo echo = new Echo({
  'broadcaster': 'pusher',
  'client': pusher,
});

echo.channel('public-channel').listen('PublicEvent', (e) {
  print(e);
});

Please assist.
Thanks

**Comment by trimmytech** [comment]
pardon me please , i entered wrong host in the configuration

**Comment by olubunmitosin** [comment]
Happy that you got it working.
Nevertheless, I will work on the package and improve it further to make it
easier to use.

Regards!
