### ISSUE TITLE
Will this package work with a private pusher server on laravel and not the Pusher microservice?

### ISSUE THREAD

**Issue by nicolasvahidzein** [olubunmitosin/laravel_flutter_pusher#2]
Hello, 

I am using Laravel WebSockets, will this work with your package or only the paid Pusher service? Thanks.

**Comment by olubunmitosin** [comment]
Hey Nicolas,

this package works for both.
I have used it with Laravel websockets severally and the result was awesome.

Let me know if you have further questions.

**Comment by nicolasvahidzein** [comment]
Wonderful, thanks buddy.
